name: Playwright – Cards Only
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cards tests
        run: npm run test:cards

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-cards
          path: playwright-report
          retention-days: 7

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml-cards
          path: test-results/junit.xml
          retention-days: 7

  report:
    if: always()
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Download HTML report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Publish JUnit to Summary and Check Run
        uses: dorny/test-reporter@v2
        with:
          artifact: junit-xml
          path: '**/*.xml'
          reporter: java-junit
          use-actions-summary: true
          fail-on-error: true
          fail-on-empty: true

      - name: Add summary
        run: |
          echo "## Playwright Report" >> $GITHUB_STEP_SUMMARY
          echo "- HTML report uploaded as artifact: **playwright-report**" >> $GITHUB_STEP_SUMMARY
          echo "- JUnit XML uploaded as artifact: **junit-xml**" >> $GITHUB_STEP_SUMMARY
          if [ -f junit-xml/junit.xml ]; then
            echo "\n<details><summary>JUnit file present</summary>" >> $GITHUB_STEP_SUMMARY
            echo "<pre>$(ls -lh junit-xml/junit.xml)</pre>" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi