name: Playwright – Checkers Only
on:
  push:
    branches: [ master ]
    paths:
      - 'utils/checkers-game/**'
      - 'tests/exercies_1/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'utils/checkers-game/**'
      - 'tests/exercies_1/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch: { }

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright (checkers project)
        id: run-tests
        run: npx playwright test --project=checkers-game || true

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-checkers
          path: tests-report/html
          if-no-files-found: warn

      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report-checkers
          path: tests-report/junit/junit.xml
          if-no-files-found: warn

      - name: Upload test artifacts (traces/screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-output-checkers
          path: tests-output
          if-no-files-found: warn

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download JUnit
        uses: actions/download-artifact@v4
        with:
          name: junit-report-checkers
          path: junit

      - name: Test Reporter (JUnit)
        uses: dorny/test-reporter@v2
        with:
          name: Playwright — Checkers
          path: junit/junit.xml
          reporter: java-junit
          fail-on-error: false